catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
     url(r'^$', views.index, name='index'),
     url(r'^books/$', views.BookListView.as_view(), name='books'),
     url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
     url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
     url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [   
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    url(r'^borrowed/$', views.LoanedBooksAllListView.as_view(), name='all-borrowed'), # Reto
]

# Add URLConf for librarian to renew a book.
urlpatterns += [   
    url(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
]

from django.urls import path
urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

locallibrary/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
# Use include() to add URLS from the catalog application
from django.conf.urls import include
# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models

# Create your models here.

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

# Clase Genero
class Genre(models.Model):
    """
    Modelo que representa el genero el libro. Ej: Ciencia ficcion, Policiaca, Aventura, Romance, etc.
    """
    name = models.CharField(max_length = 200, verbose_name = "Nombre de Genero",
           help_text = "Entre el genero del libro. Ej: Ciencia ficcion, Policiaca, Aventura, Romance, etc.)" )
    
    def __str__(self):
        """
        Cadena para representar el objeto (en el sitio de administración, etc.)
        """
        return self.name

class Language(models.Model):
    """
    Modelo que representa el Lenguage (Ej: Ingles, Frances, Japones, etc.)
    """
    name = models.CharField(max_length=200, verbose_name = "Nombre Lenguaje", help_text="Entre el lenguaje natural del libro. (Ej: Ingles, Frances, Japanes, etc)")
    
    def __str__(self):
        """
        Cadena para representar el objeto (en el sitio de administración, etc.)
        """
        return self.name

# Clase Libro
class Book(models.Model):
    """
    Modelo que representa un libro(pero no la instancia del libro.)
    """
    title = models.CharField(max_length=200, verbose_name = "Titulo", help_text="Entre el titulo del libro")
    # Author - Clave foranea. Se usa porque el libro solo puede tener un autor, pero los autores pueden tener varios libros
    # Author como una cadena en lugar de un objeto porque todavía no se ha declarado en el archivo.
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True, verbose_name = "Autor", help_text="Seleccione el nombre del autor")
    summary = models.TextField(max_length=1000, verbose_name = "Descripcion", help_text="Entre una breve descripcion del libro.")
    # Enlace a la pagina de: International ISBN Agency
    isbn = models.CharField('ISBN',max_length=13, help_text='Entre 13 Caracteres de <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    # ManyToManyField se usa porque un libro puede tener muchos generos. Los libros pueden abarcar muchos generos.
    # La clase Genre ya se definio.
    genre = models.ManyToManyField(Genre, verbose_name="Genero", help_text="Seleccione un genero para el libro.")
    language = models.ForeignKey('Language', verbose_name ="Lenguaje", on_delete=models.SET_NULL, null=True, help_text="Entre el Lenguaje")
    
    def nombre_genero(self):
        """
        Crea una cadena para el Genero. Esto es requerido para desplegar el genero en Interface Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
        display_genre.short_description = 'Genero'

    def get_absolute_url(self):
        """
        Devuelve la url para acceder a una instancia de un libro en particular.
        """
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        """
        Cadena para representar el objeto (en el sitio de administración, etc.)
        """
        return self.title

# Clase Instancias del Libro
import uuid # Required for unique book instances
from datetime import date
from django.contrib.auth.models import User # Requirido para asignar a un usuario un prestamo

class BookInstance(models.Model):
    """
    Modelo que representa una copia especifica de un libro(Ej: Libro que puede ser prestado).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, verbose_name = "ID",
         help_text="ID unico para el libro en toda la Libreria")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, verbose_name = "Libro", help_text="Seleccione el libro", null=True) 
    imprint = models.CharField(max_length=200, verbose_name = "Version", help_text="Entre la version")
    due_back = models.DateField(null=True, blank=True, verbose_name = "Fecha reintegro", help_text="Entre la fecha de reintegro")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Mantenimiento'),
        ('o', 'Prestado'),
        ('a', 'Disponible'),
        ('r', 'Reservado'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', verbose_name = "Disponibilidad", help_text='Seleccione la Disponibilidad')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)
        
    def __str__(self):
        """
        Cadena para representar el objeto (en el sitio de administración, etc.)
        """
        return '%s (%s)' % (self.id,self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
	
# Clase Autor del Libro (se asume un autor por libro)
class Author(models.Model):
    """
    Modelo que representa el autor.
    """
    first_name = models.CharField(max_length=100, verbose_name = "Primer Nombre")
    last_name = models.CharField(max_length=100, verbose_name = "Segundo Apellido")
    date_of_birth = models.DateField(null=True, blank=True, verbose_name = "Fecha Nacimiento")
    date_of_death = models.DateField('Fallecido', null=True, blank=True)
    
    def get_absolute_url(self):
        """
        Returna el url para acceder a una instancia del autor.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s, %s' % (self.last_name, self.first_name)

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.
    
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Entre una fecha entre hoy y 4 semanas (defecto 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        #Check date is not in past. 
        if data < datetime.date.today():
            raise ValidationError(_('Fecha Invalida - Renovacion en el pasado'))

        #Check date is in range librarian allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Fecha Invalida - Renovacion superior a 4 semanas'))

        # Remember to always return the cleaned data.
        return data

catalog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Book, Author, BookInstance, Genre

def index(request):
    """
    Funcion que muestra la pagina principal del sitio
    """
    # Genera las cantidades de agunos objetos
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Libros disponibles (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()  # The 'all()' is implied by default.
    # Numero de Generos
    num_genres = Genre.objects.all().count()
    # Numero de libros que contienen la palabra 'el' 
    num_libros_palabra_el = Book.objects.filter(title__icontains='el').count()

    # Numero de visitas a esta pagina.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    
    # Dibuja la plantilla HTML index.html con los datos en la variable context
    return render(
        request,
        'index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,
                 'num_authors':num_authors,'num_genres':num_genres,'num_libros_palabra_el':num_libros_palabra_el,
                 'num_visits':num_visits}, 
    )

from django.views import generic

class BookListView(generic.ListView):
    model = Book
    paginate_by = 4 
    context_object_name = 'lista_libros'   # Nombre para la lista como una variable de plantilla
    queryset = Book.objects.filter(title__icontains='') # Obtiene libros con la palabra '' en el titulo
#    queryset = Book.objects.filter(title__icontains='A')[:3] # Obtiene 5 libros con la palabrea 'A' en el titulo
#    queryset = Book.objects.all # Obtiene todos los libros . Pero no funciona la paginacion.

    template_name = 'catalog/book_list.html'  # Especifica el nombre/ubicación de plantilla
	
class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 4
    context_object_name = 'lista_autores'   # Nombre para la lista como una variable de plantilla
    queryset = Author.objects.filter(last_name__icontains='') # Obtiene con la palabraa '' en el primer nombre
#    queryset = Author.objects.filter(last_name__icontains='A')[:5] # Obtiene 5 autores con la palabrea 'A' en el primer nombre
#    queryset = Author.objects.all # Obtiene todos los autores. Pero no funciona la paginacion.
    template_name = 'catalog/author_list.html'  # Especifica el nombre/ubicación de plantilla.
	
class AuthorDetailView(generic.DetailView):
    model = Author

from django.contrib.auth.mixins import LoginRequiredMixin
class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Generic class-based view listing books on loan to current user. 
    """
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

# Reto
from django.contrib.auth.mixins import PermissionRequiredMixin

class LoanedBooksAllListView(PermissionRequiredMixin,generic.ListView):
    """
    Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission.
    """
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name ='catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 4
    
    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')  

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
#from django.core.urlresolvers import reverse
from django.urls import reverse
import datetime
from django.contrib.auth.decorators import permission_required

from .forms import RenewBookForm

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst=get_object_or_404(BookInstance, pk = pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})

    
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Author, Book

class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    initial={'date_of_death':'05/01/2018',}

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    initial={'date_of_death':'05/01/2018',}

class BookUpdate(UpdateView):
    model = Book
    fields = ['title','author','summary','isbn', 'genre', 'language']

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Borrar Autor</h1>

<p>Seguro de borrar el libro: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Si, borre." />
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Autor: {{ author.first_name }}, {{ author.last_name }}</h1>

  <p>{{ author.date_of_birth }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4><font size=6, color="green">Libros</font></h4>

    {% for copy in author.book_set.all %}
		<p><font size=4, color="teal">{{copy.title}}</font></p>
		<p class="text-muted">{{copy.summary}}</p>
    {% endfor %}
	
  </div>
  
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lista de autores</h1>

    {% if lista_autores %}
    <ul>

      {% for author in lista_autores %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name}} {{author.last_name}} </a> 
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hay autores en esta libreria.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Borrar Libro</h1>

<p>Seguro de borrar el libro: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Si, borre." />
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Titulo: {{ book.title }}</h1>

  <p><strong>Autor:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- El enlace al detalle del autor detail no esta aun definido -->
  <p><strong>Descripcion:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Lenguaje:</strong> {{ book.language }}</p>  
  <p><strong>Genero:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copias</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Fecha devolucion:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Version:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>ID:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lista de libros</h1>

    {% if lista_libros %}
    <ul>

      {% for book in lista_libros %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hay libros en esta libreria.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renovacion: {{bookinst.book.title}}</h1>
    <p>Prestario: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Fecha Prestamo: {{bookinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Aceptar" />
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Libros Prestados</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %} 
					{% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renovacion</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay libros prestados.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Prestamo de Libros</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay libros prestados.</p>
    {% endif %}       
{% endblock %}